---
title: " Environmental Sciences - Data Collection, Storage & Management - HOBO Exerciese 3"
author: "Neisse N"
date: "15/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Setting stage

Packages in use

```{r packages, message=FALSE, warning=FALSE}
library(readr)
library(tidyverse)
library(lubridate)
library(rmarkdown)
library(rio)
library(zoo) # rollapply
```

Loading-in data

```{r data upload, message=FALSE, warning=FALSE}

rm(list=ls(all=TRUE))
df <- read_csv("C:/Users/NeoN/Desktop/2020FreiburgEnvironmentalSciences/Semester/Semester1/Data- Storage Collection & Managment/data/raw-data/10347371.csv")


dfh_umg <- read_csv('C:/Users/NeoN/Desktop/2020FreiburgEnvironmentalSciences/Semester/Semester1/Data- Storage Collection & Managment/data/10347371_TH.csv')

df <- as.tibble(df)
dfh_umg <- as.tibble(dfh_umg)

#df_raw <- read_csv('https://raw.githubusercontent.com/NeisseN/EnvironmentalScience/main/data-%20storage%2C%20collection%20%26%20management/data/hobo/raw/10347371_2020.12.21_15.26.csv') # does work!

```

## 1. Temperature indices
#### 1.1 Mean temperatures

```{r means}

dfh_umg %>% 
  summarise(Tavg = round(mean(th), 3))

dfh_umg %>% 
  mutate(hour = hour(date_time)) %>% 
  mutate(dn = if_else(hour >= 6 & hour < 18,
                      'd', 'n',)) %>% 
  group_by(dn) %>% 
  summarise(Tdn = round(mean(th), 3)) %>% 
  ungroup %>% 
  summarise(diff(Tdn))

dfh_umg %>% 
  mutate(hour = hour(date_time)) %>% 
  mutate(dn = if_else(hour >= 6 & hour < 18,
                      'd', 'n',)) %>% 
  group_by(dn) %>% 
  summarise(Tdn = mean(th)) %>% 
  ungroup %>% # same can be done within summarise (,.groups = 'drop')
  summarise(Td = round(diff(Tdn),3))

```
#### 1.2 Mean daily amplitude

```{r amplitude}

dfh_umg %>%
  mutate(date = date(date_time)) %>% 
  group_by(date) %>% 
  summarise(Tmin = min(th), Tmax = max(th)) %>% 
  ungroup %>% 
  mutate(Td = Tmax - Tmin) %>% 
  summarise(Tamp = round(mean(Td), 3))

```

#### 1.3 Most rapid temperature change

```{r}

t_range <- function(x) abs(diff(range(x)))

dfh_umg %>%
  mutate(t06 = rollapply(th,
                         width = 6,
                         FUN = t_range,
                         fill = 0,
                         partial = TRUE)) %>% 
  filter(t06 == max(t06))

```

#### 1.4 Fraction of NA-Values

```{r}

dfh_umg$origin <- as.factor(dfh_umg$origin)

dfh_umg %>% 
  group_by(origin) %>% 
  count() %>%
  ungroup %>% 
  summarise(Tfrc = n / sum(n))

```


## 2. Light intensity indices


```{r light indices}

df %>% 
  filter(lux > 0) %>% 
  summarise(Lavg = round(mean(lux),3))

df %>% 
  mutate(hm = format(date_time, format = '%H:%M')) %>% 
  group_by(hm) %>% 
  summarise(Lmean = mean(lux)) %>% 
  filter(Lmean == max(Lmean))

```

## 4. Comparison with a long-term average

```{r long-term average}

DWD_long <- read_delim("air_temp_19510101_20191231_01443.txt", 
                        ";", escape_double = FALSE, trim_ws = TRUE)

DWD_lon <- DWD_long %>%
  select(MESS_DATUM, TT_TU) %>% 
  set_colnames(c("date_time","th")) %>% 
  mutate(date_time = parse_date_time(date_time, orders = "Ymdh")) %>% 
  mutate(day = day(date_time),
         month = month(date_time),
         year = year(date_time)) %>% 
  filter(year(date_time)>=1999 & year(date_time)<=2019) #to have only 20 years

DWD_lon_trunc <- DWD_lon %>% 
  group_by(year) %>% 
  filter(month(date_time)==11 & day(date_time)== 30 | 
        month(date_time)== 12 & day(date_time) >=1 & day(date_time) < 21) %>% #Leons solution!  
  ungroup()

DWD_mean <- DWD_lon_trunc %>% 
  select("date_time","th","year") %>% 
  group_by(year) %>% 
  summarise(mean = mean(th))

```

